// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using Artemis.System;
using UnityEngine;

public class TestProcessor : EntityComponentProcessingSystem<TestComp1>
{
	public TestProcessor ()
	{
	}

	public override void OnAdded (Artemis.Entity entity)
	{
		Debug.Log(EntitySystem.BlackBoard.GetEntry<TestProcessor>("test1"));
	}

	public override void Process (Artemis.Entity entity, TestComp1 component1)
	{
		//Debug.Log("aaaa " + entity.UniqueId);

	}
}


